<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Nudge</text>

        <Action name="nudgeLeftAction">
        <icon></icon>
        <text>Nudge Left</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>left</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="nudgeRightAction">
        <icon></icon>
        <text>Nudge Right</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>right</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="nudgeUpAction">
        <icon></icon>
        <text>Nudge Up</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>up</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="nudgeDownAction">
        <icon></icon>
        <text>Nudge Down</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>down</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>